### ISSUE TITLE
Create changelog

### ISSUE THREAD

**Issue by masseelch** [masseelch/FastTrackBalancing#12]
@flocke159 Your part :heart:

**Comment by flocke159** [comment]
[Changelog FTB 2.0.pdf](https://github.com/masseelch/FastTrackBalancing/files/7923586/Changelog.FTB.2.0.pdf)

**Comment by masseelch** [comment]
https://github.com/masseelch/FastTrackBalancing/commit/3ceb7630262cc43c79531f5450ad18b8aff6d7d1
