### ISSUE TITLE
Bugfixes before release of 4.0.0

### ISSUE THREAD

**Issue by miesmus** [masseelch/FastTrackBalancing#28]
Bannockburn:
- [x] +5 CS in home territory do not apply
- [x] +2 Movement for military land-units do not apply
- [x] Check whether the "+5 CS in home territory" needs an own LOC_Tag that displays its singular bonus in the pre-combat analysis of units in question (similiar to the highlander-bug mentioned below)

Minor Bugfixes:

- [ ] LOC_Building..._Domination --> Search and Rescue
- [x] Render "Zufriedene Städte" into "Glückliche" Städte in the german translation of CA 'Scottis Enlightenment', render "all" into "alle"
- [x] LOC_Tag_..._Highlander --> Description of the +5 CS on hills is missing in the pre-combat-analysis of the highlander, although the +5 CS are added to the total value of CS.

**Comment by masseelch** [comment]
@miesmus My part is done.
